version: '3.2'

# ports : host:container
services:
  mxtest:
    build: .
    image: fredmoser/mx-app-test:0.1-go
    ports:
      - 8080:8080
    volumes:
      - ./:/web

  nodejs:
    image: node:10.14.1
    user: node
    working_dir: /home/node/app
    volumes:
      - ./server/:/home/node/app
    ports:
      - 8081:8081
    command: sh -c "npm install && npm start"
